return function()
    return {
        workspace.Towers.ToOH.Obby:GetChildren()[41],
        workspace.Towers.ToOH.Obby:GetChildren()[74],
        workspace.Towers.ToOH.Obby:GetChildren()[78],
        workspace.Towers.ToOH.Obby:GetChildren()[77],
        workspace.Towers.ToOH.Obby:GetChildren()[80],
        workspace.Towers.ToOH.Obby:GetChildren()[81],
        workspace.Towers.ToOH.Obby:GetChildren()[88],
        workspace.Towers.ToOH.Obby:GetChildren()[83],
        workspace.Towers.ToOH.Obby:GetChildren()[131],
        workspace.Towers.ToOH.Obby:GetChildren()[132],
        workspace.Towers.ToOH.Obby:GetChildren()[84],
        workspace.Towers.ToOH.Obby:GetChildren()[85],
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[1]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[75],
        workspace.Towers.ToOH.Obby:GetChildren()[93],
        workspace.Towers.ToOH.Obby:GetChildren()[65],
        workspace.Towers.ToOH.Obby:GetChildren()[94],
        workspace.Towers.ToOH.Obby:GetChildren()[66],
        workspace.Towers.ToOH.Obby:GetChildren()[98],
        workspace.Towers.ToOH.Obby:GetChildren()[119],
        -- [MISSING] Motor  was at (1163.33, 2207.08, 2223.37)
        workspace.Towers.ToOH.Obby:GetChildren()[99],
        workspace.Towers.ToOH.Obby:GetChildren()[805],
        workspace.Towers.ToOH.Obby:GetChildren()[103],
        workspace.Towers.ToOH.Obby:GetChildren()[102],
        workspace.Towers.ToOH.Obby:GetChildren()[101],
        workspace.Towers.ToOH.Obby:GetChildren()[106],
        workspace.Towers.ToOH.Obby:GetChildren()[104],
        workspace.Towers.ToOH.Obby:GetChildren()[107],
        workspace.Towers.ToOH.Obby:GetChildren()[105],
        workspace.Towers.ToOH.Obby:GetChildren()[129],
        workspace.Towers.ToOH.Obby:GetChildren()[44],
        workspace.Towers.ToOH.Obby:GetChildren()[803],
        workspace.Towers.ToOH.Obby:GetChildren()[791],
        workspace.Towers.ToOH.Obby:GetChildren()[220],
        workspace.Towers.ToOH.Obby:GetChildren()[34],
        workspace.Towers.ToOH.Obby:GetChildren()[133],
        -- [MISSING] Part  was at (1114.33, 2251.09, 2259.37)
        -- [MISSING] Part  was at (1120.33, 2253.09, 2250.37)
        workspace.Towers.ToOH.Obby:GetChildren()[117],
        workspace.Towers.ToOH.Obby:GetChildren()[120],
        workspace.Towers.ToOH.Obby:GetChildren()[250],
        workspace.Towers.ToOH.Obby:GetChildren()[439],
        -- [MISSING] Part  was at (1155.83, 2263.59, 2236.37)
        -- [MISSING] Part  was at (1160.83, 2267.59, 2228.37)
        -- [MISSING] Part  was at (1160.83, 2258.60, 2216.87)
        workspace.Towers.ToOH.Obby:GetChildren()[121],
        workspace.Towers.ToOH.Obby:GetChildren()[115],
        workspace.Towers.ToOH.Obby:GetChildren()[122],
        workspace.Towers.ToOH.Obby:GetChildren()[283],
        workspace.Towers.ToOH.Obby:GetChildren()[771],
        -- [MISSING] Part  was at (1146.52, 2288.07, 2188.30)
        -- [MISSING] Part  was at (1134.33, 2292.96, 2184.37)
        -- [MISSING] Part  was at (1124.28, 2295.07, 2184.37)
        -- [MISSING] Part  was at (1124.28, 2303.07, 2197.37)
        workspace.Towers.ToOH.Obby:GetChildren()[123],
        -- [MISSING] Part  was at (1116.33, 2312.08, 2217.37)
        workspace.Towers.ToOH.Obby:GetChildren()[126],
        -- [MISSING] Part  was at (1124.33, 2311.07, 2240.37)
        -- [MISSING] Part  was at (1124.33, 2327.07, 2240.37)
        workspace.Towers.ToOH.Obby:GetChildren()[128],
        workspace.Towers.ToOH.Obby:GetChildren()[127],
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[112],
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[2]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[51],
        workspace.Towers.ToOH.Obby:GetChildren()[111],
        -- [MISSING] ButtonDeactivator  was at (1179.33, 2353.07, 2236.37)
        workspace.Towers.ToOH.Frame:GetChildren()[23],
        workspace.Towers.ToOH.Obby:GetChildren()[200],
        workspace.Towers.ToOH.Obby:GetChildren()[252],
        workspace.Towers.ToOH.Obby:GetChildren()[199],
        workspace.Towers.ToOH.Obby:GetChildren()[262],
        workspace.Towers.ToOH.Obby:GetChildren()[134],
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[4]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[136],
        workspace.Towers.ToOH.Obby:GetChildren()[137],
        workspace.Towers.ToOH.Obby:GetChildren()[135],
        workspace.Towers.ToOH.Obby:GetChildren()[146],
        -- [MISSING] Part  was at (1207.83, 2369.62, 2183.87)
        workspace.Towers.ToOH.Obby:GetChildren()[148],
        -- [MISSING] Part  was at (1222.80, 2406.07, 2208.87)
        workspace.Towers.ToOH.Obby:GetChildren()[149],
        workspace.Towers.ToOH.Obby:GetChildren()[37],
        workspace.Towers.ToOH.Obby:GetChildren()[39],
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[3]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[54],
        workspace.Towers.ToOH.Obby:GetChildren()[40],
        -- [MISSING] Part  was at (1208.33, 2417.06, 2271.82)
        -- [MISSING] Part  was at (1207.83, 2433.56, 2270.87)
        workspace.Towers.ToOH.Obby:GetChildren()[171],
        workspace.Towers.ToOH.Obby:GetChildren()[179],
        workspace.Towers.ToOH.Obby:GetChildren()[180],
        workspace.Towers.ToOH.Obby:GetChildren()[176],
        workspace.Towers.ToOH.Obby:GetChildren()[166],
        workspace.Towers.ToOH.Obby:GetChildren()[163],
        workspace.Towers.ToOH.Obby:GetChildren()[186],
        workspace.Towers.ToOH.Obby:GetChildren()[185],
        workspace.Towers.ToOH.Obby:GetChildren()[161],
        -- [MISSING] Part  was at (1203.33, 2437.03, 2289.37)
        workspace.Towers.ToOH.Obby:GetChildren()[159],
        workspace.Towers.ToOH.Obby:GetChildren()[204],
        workspace.Towers.ToOH.Obby:GetChildren()[206],
        workspace.Towers.ToOH.Obby:GetChildren()[205],
        workspace.Towers.ToOH.Obby:GetChildren()[209],
        workspace.Towers.ToOH.Obby:GetChildren()[212],
        workspace.Towers.ToOH.Obby:GetChildren()[211],
        workspace.Towers.ToOH.Obby:GetChildren()[210],
        workspace.Towers.ToOH.Frame:GetChildren()[6],
        workspace.Towers.ToOH.Obby:GetChildren()[188],
        workspace.Towers.ToOH.Obby:GetChildren()[189],
        workspace.Towers.ToOH.Obby:GetChildren()[190],
        workspace.Towers.ToOH.Obby:GetChildren()[191],
        workspace.Towers.ToOH.Obby:GetChildren()[257],
        -- [MISSING] Part  was at (1143.38, 2355.06, 2308.37)
        workspace.Towers.ToOH.Obby:GetChildren()[312],
        workspace.Towers.ToOH.Obby:GetChildren()[195],
        workspace.Towers.ToOH.Obby:GetChildren()[196],
        workspace.Towers.ToOH.Obby:GetChildren()[197],
        workspace.Towers.ToOH.Obby:GetChildren()[198],
        workspace.Towers.ToOH.Obby:GetChildren()[201],
        -- [MISSING] Conveyor  was at (1067.33, 2361.07, 2290.37)
        -- [MISSING] Conveyor  was at (1052.33, 2361.57, 2296.37)
        workspace.Towers.ToOH.Obby:GetChildren()[202],
        workspace.Towers.ToOH.Obby:GetChildren()[203],
        -- [MISSING] Part  was at (1030.83, 2368.57, 2291.91)
        workspace.Towers.ToOH.Obby:GetChildren()[218],
        workspace.Towers.ToOH.Obby:GetChildren()[217],
        workspace.Towers.ToOH.Obby:GetChildren()[219],
        -- [MISSING] Part  was at (1061.32, 2363.56, 2195.39)
        workspace.Towers.ToOH.Obby:GetChildren()[769],
        workspace.Towers.ToOH.Obby:GetChildren()[229],
        workspace.Towers.ToOH.Obby:GetChildren()[313],
        workspace.Towers.ToOH.Obby:GetChildren()[224],
        -- [MISSING] Part  was at (1049.33, 2369.56, 2219.37)
        -- [MISSING] Part  was at (1056.33, 2371.56, 2227.37)
        workspace.Towers.ToOH.Obby:GetChildren()[216],
        workspace.Towers.ToOH.Obby:GetChildren()[228],
        workspace.Towers.ToOH.Obby:GetChildren()[226],
        workspace.Towers.ToOH.Obby:GetChildren()[227],
        workspace.Towers.ToOH.Obby:GetChildren()[241],
        workspace.Towers.ToOH.Obby:GetChildren()[230],
        workspace.Towers.ToOH.Obby:GetChildren()[231],
        workspace.Towers.ToOH.Obby:GetChildren()[242],
        workspace.Towers.ToOH.Obby:GetChildren()[232],
        workspace.Towers.ToOH.Obby:GetChildren()[239],
        workspace.Towers.ToOH.Obby:GetChildren()[237],
        workspace.Towers.ToOH.Obby:GetChildren()[92],
        workspace.Towers.ToOH.Obby:GetChildren()[245],
        workspace.Towers.ToOH.Obby:GetChildren()[247],
        workspace.Towers.ToOH.Obby:GetChildren()[248],
        workspace.Towers.ToOH.Obby:GetChildren()[249],
        -- [MISSING] Part  was at (1091.38, 2411.55, 2206.29)
        -- [MISSING] Part  was at (1091.25, 2427.54, 2206.38)
        workspace.Towers.ToOH.Obby:GetChildren()[256],
        -- [MISSING] Part  was at (1091.33, 2435.56, 2223.37)
        -- [MISSING] Part  was at (1087.33, 2440.56, 2231.37)
        -- [MISSING] Part  was at (1083.33, 2444.56, 2223.37)
        workspace.Towers.ToOH.Obby:GetChildren()[371],
        workspace.Towers.ToOH.Obby:GetChildren()[265],
        workspace.Towers.ToOH.Obby:GetChildren()[290],
        workspace.Towers.ToOH.Obby:GetChildren()[258],
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[5]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[259],
        workspace.Towers.ToOH.Obby:GetChildren()[370],
        workspace.Towers.ToOH.Obby:GetChildren()[263],
        workspace.Towers.ToOH.Obby:GetChildren()[215],
        workspace.Towers.ToOH.Obby:GetChildren()[270],
        workspace.Towers.ToOH.Obby:GetChildren()[271],
        workspace.Towers.ToOH.Obby:GetChildren()[273],
        workspace.Towers.ToOH.Obby:GetChildren()[272],
        workspace.Towers.ToOH.Obby:GetChildren()[277],
        -- [MISSING] Part  was at (1135.38, 2452.07, 2203.37)
        -- [MISSING] Part  was at (1135.33, 2452.06, 2203.37)
        workspace.Towers.ToOH.Obby:GetChildren()[276],
        workspace.Towers.ToOH.Obby:GetChildren()[274],
        workspace.Towers.ToOH.Obby:GetChildren()[280],
        workspace.Towers.ToOH.Obby:GetChildren()[281],
        -- [MISSING] Motor  was at (1135.33, 2448.22, 2266.46)
        workspace.Towers.ToOH.Obby:GetChildren()[287],
        workspace.Towers.ToOH.Obby:GetChildren()[289],
        -- [MISSING] Part  was at (1149.83, 2447.07, 2244.35)
        -- [MISSING] Part  was at (1150.12, 2449.10, 2213.93)
        -- [MISSING] Part  was at (1149.82, 2449.01, 2198.87)
        workspace.Towers.ToOH.Obby:GetChildren()[291],
        workspace.Towers.ToOH.Obby:GetChildren()[293],
        workspace.Towers.ToOH.Obby:GetChildren()[304],
        workspace.Towers.ToOH.Obby:GetChildren()[305],
        workspace.Towers.ToOH.Obby:GetChildren()[444],
        workspace.Towers.ToOH.Obby:GetChildren()[307],
        workspace.Towers.ToOH.Obby:GetChildren()[308],
        workspace.Towers.ToOH.Obby:GetChildren()[310],
        workspace.Towers.ToOH.Obby:GetChildren()[441],
        workspace.Towers.ToOH.Obby:GetChildren()[314],
        workspace.Towers.ToOH.Obby:GetChildren()[315],
        workspace.Towers.ToOH.Obby:GetChildren()[311],
        workspace.Towers.ToOH.Obby:GetChildren()[317],
        workspace.Towers.ToOH.Obby:GetChildren()[326],
        workspace.Towers.ToOH.Obby:GetChildren()[321],
        workspace.Towers.ToOH.Obby:GetChildren()[330],
        workspace.Towers.ToOH.Obby:GetChildren()[318],
        -- [MISSING] Conveyor  was at (1161.33, 2448.06, 2215.37)
        workspace.Towers.ToOH.Obby:GetChildren()[327],
        workspace.Towers.ToOH.Obby:GetChildren()[770],
        workspace.Towers.ToOH.Obby:GetChildren()[331],
        workspace.Towers.ToOH.Obby:GetChildren()[334],
        workspace.Towers.ToOH.Obby:GetChildren()[336],
        workspace.Towers.ToOH.Obby:GetChildren()[339],
        workspace.Towers.ToOH.Obby:GetChildren()[344],
        workspace.Towers.ToOH.Obby:GetChildren()[443],
        workspace.Towers.ToOH.Frame:GetChildren()[61],
        -- [MISSING] Destination  was at (1176.33, 2454.56, 2183.37)
        workspace.Towers.ToOH.Obby:GetChildren()[340],
        workspace.Towers.ToOH.Obby:GetChildren()[341],
        workspace.Towers.ToOH.Obby:GetChildren()[342],
        -- [MISSING] Conveyor  was at (1206.33, 2448.06, 2190.87)
        -- [MISSING] Conveyor  was at (1206.33, 2448.06, 2204.87)
        workspace.Towers.ToOH.Obby:GetChildren()[346],
        workspace.Towers.ToOH.Obby:GetChildren()[347],
        workspace.Towers.ToOH.Obby:GetChildren()[345],
        workspace.Towers.ToOH.Obby:GetChildren()[521],
        workspace.Towers.ToOH.Obby:GetChildren()[513],
        workspace.Towers.ToOH.Obby:GetChildren()[360],
        workspace.Towers.ToOH.Obby:GetChildren()[361],
        workspace.Towers.ToOH.Obby:GetChildren()[362],
        workspace.Towers.ToOH.Obby:GetChildren()[359],
        workspace.Towers.ToOH.Obby:GetChildren()[352],
        workspace.Towers.ToOH.Obby:GetChildren()[365],
        workspace.Towers.ToOH.Obby:GetChildren()[351],
        workspace.Towers.ToOH.Obby:GetChildren()[363],
        workspace.Towers.ToOH.Obby:GetChildren()[354],
        workspace.Towers.ToOH.Obby:GetChildren()[355],
        workspace.Towers.ToOH.Obby:GetChildren()[358],
        workspace.Towers.ToOH.Obby:GetChildren()[356],
        workspace.Towers.ToOH.Obby:GetChildren()[357],
        -- [MISSING] Part  was at (1163.73, 2485.06, 2291.37)
        -- [MISSING] Part  was at (1161.09, 2486.78, 2291.37)
        -- [MISSING] Part  was at (1143.17, 2486.84, 2291.37)
        -- [MISSING] Part  was at (1137.13, 2485.31, 2291.33)
        workspace.Towers.ToOH.Obby:GetChildren()[254],
        workspace.Towers.ToOH.Obby:GetChildren()[369],
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[6]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[266],
        workspace.Towers.ToOH.Obby:GetChildren()[255],
        workspace.Towers.ToOH.Obby:GetChildren()[504],
        workspace.Towers.ToOH.Obby:GetChildren()[478],
        workspace.Towers.ToOH.Obby:GetChildren()[410],
        workspace.Towers.ToOH.Obby:GetChildren()[378],
        workspace.Towers.ToOH.Obby:GetChildren()[377],
        workspace.Towers.ToOH.Obby:GetChildren()[381],
        -- [MISSING] Kill Brick  was at (1051.33, 2472.63, 2275.26)
        workspace.Towers.ToOH.Obby:GetChildren()[385],
        workspace.Towers.ToOH.Obby:GetChildren()[384],
        workspace.Towers.ToOH.Obby:GetChildren()[387],
        workspace.Towers.ToOH.Obby:GetChildren()[389],
        workspace.Towers.ToOH.Obby:GetChildren()[407],
        workspace.Towers.ToOH.Obby:GetChildren()[394],
        workspace.Towers.ToOH.Obby:GetChildren()[388],
        workspace.Towers.ToOH.Obby:GetChildren()[402],
        workspace.Towers.ToOH.Obby:GetChildren()[401],
        workspace.Towers.ToOH.Obby:GetChildren()[411],
        workspace.Towers.ToOH.Obby:GetChildren()[413],
        workspace.Towers.ToOH.Obby:GetChildren()[412],
        workspace.Towers.ToOH.Obby:GetChildren()[414],
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[7]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[399],
        workspace.Towers.ToOH.Obby:GetChildren()[400],
        workspace.Towers.ToOH.Obby:GetChildren()[409],
        -- [MISSING] Part  was at (1051.33, 2508.08, 2203.37)
        workspace.Towers.ToOH.Obby:GetChildren()[419],
        -- [MISSING] Conveyor  was at (1058.11, 2492.56, 2182.37)
        workspace.Towers.ToOH.Obby:GetChildren()[420],
        -- [MISSING] Conveyor  was at (1068.74, 2503.85, 2182.37)
        workspace.Towers.ToOH.Obby:GetChildren()[440],
        workspace.Towers.ToOH.Obby:GetChildren()[418],
        workspace.Towers.ToOH.Obby:GetChildren()[46],
        workspace.Towers.ToOH.Obby:GetChildren()[430],
        workspace.Towers.ToOH.Obby:GetChildren()[95],
        -- [MISSING] Part  was at (1105.33, 2520.56, 2182.37)
        workspace.Towers.ToOH.Obby:GetChildren()[429],
        workspace.Towers.ToOH.Obby:GetChildren()[298],
        workspace.Towers.ToOH.Obby:GetChildren()[428],
        workspace.Towers.ToOH.Obby:GetChildren()[427],
        workspace.Towers.ToOH.Obby:GetChildren()[426],
        -- [MISSING] Part  was at (1138.33, 2524.61, 2203.37)
        workspace.Towers.ToOH.Obby:GetChildren()[423],
        workspace.Towers.ToOH.Obby:GetChildren()[459],
        workspace.Towers.ToOH.Obby:GetChildren()[460],
        workspace.Towers.ToOH.Obby:GetChildren()[461],
        -- [MISSING] Part  was at (1171.33, 2561.56, 2214.37)
        workspace.Towers.ToOH.Obby:GetChildren()[470],
        workspace.Towers.ToOH.Obby:GetChildren()[471],
        workspace.Towers.ToOH.Obby:GetChildren()[465],
        workspace.Towers.ToOH.Obby:GetChildren()[466],
        workspace.Towers.ToOH.Obby:GetChildren()[472],
        workspace.Towers.ToOH.Obby:GetChildren()[473],
        workspace.Towers.ToOH.Obby:GetChildren()[474],
        -- [MISSING] Conveyor  was at (1161.33, 2569.56, 2270.37)
        -- [MISSING] Part  was at (1172.33, 2570.61, 2270.37)
        workspace.Towers.ToOH.Obby:GetChildren()[482],
        -- [MISSING] Kill Brick  was at (1145.83, 2466.56, 2245.37)
        workspace.Towers.ToOH.Obby:GetChildren()[483],
        workspace.Towers.ToOH.Obby:GetChildren()[487],
        workspace.Towers.ToOH.Obby:GetChildren()[490],
        -- [MISSING] Part  was at (1094.33, 2589.56, 2258.37)
        -- [MISSING] Part  was at (1094.33, 2590.60, 2258.37)
        workspace.Towers.ToOH.Obby:GetChildren()[493],
        workspace.Towers.ToOH.Obby:GetChildren()[538],
        workspace.Towers.ToOH.Obby:GetChildren()[499],
        workspace.Towers.ToOH.Obby:GetChildren()[539],
        workspace.Towers.ToOH.Obby:GetChildren()[500],
        workspace.Towers.ToOH.Obby:GetChildren()[643],
        workspace.Towers.ToOH.Obby:GetChildren()[502],
        workspace.Towers.ToOH.Obby:GetChildren()[522],
        workspace.Towers.ToOH.Obby:GetChildren()[519],
        workspace.Towers.ToOH.Obby:GetChildren()[511],
        -- [MISSING] Part  was at (1122.33, 2617.56, 2194.37)
        workspace.Towers.ToOH.Obby:GetChildren()[515],
        workspace.Towers.ToOH.Obby:GetChildren()[508],
        workspace.Towers.ToOH.Obby:GetChildren()[525],
        workspace.Towers.ToOH.Obby:GetChildren()[510],
        workspace.Towers.ToOH.Obby:GetChildren()[509],
        workspace.Towers.ToOH.Obby:GetChildren()[501],
        -- [MISSING] Part  was at (1141.33, 2631.57, 2236.37)
        workspace.Towers.ToOH.Obby:GetChildren()[642],
        workspace.Towers.ToOH.Obby:GetChildren()[634],
        workspace.Towers.ToOH.Obby:GetChildren()[528],
        workspace.Towers.ToOH.Obby:GetChildren()[527],
        workspace.Towers.ToOH.Obby:GetChildren()[533],
        workspace.Towers.ToOH.Obby:GetChildren()[534],
        -- [MISSING] Conveyor  was at (1202.85, 2648.63, 2236.38)
        workspace.Towers.ToOH.Obby:GetChildren()[542],
        workspace.Towers.ToOH.Obby:GetChildren()[537],
        workspace.Towers.ToOH.Obby:GetChildren()[536],
        workspace.Towers.ToOH.Obby:GetChildren()[544],
        -- [MISSING] Part  was at (1203.81, 2636.06, 2212.25)
        workspace.Towers.ToOH.Obby:GetChildren()[547],
        workspace.Towers.ToOH.Obby:GetChildren()[549],
        workspace.Towers.ToOH.Obby:GetChildren()[555],
        workspace.Towers.ToOH.Obby:GetChildren()[556],
        -- [MISSING] Conveyor  was at (1182.34, 2663.56, 2193.38)
        workspace.Towers.ToOH.Obby:GetChildren()[581],
        -- [MISSING] Conveyor  was at (1195.34, 2663.56, 2179.38)
        workspace.Towers.ToOH.Obby:GetChildren()[582],
        -- [MISSING] Part  was at (1202.84, 2663.56, 2169.88)
        workspace.Towers.ToOH.Obby:GetChildren()[541],
        -- [MISSING] Conveyor  was at (1204.23, 2665.78, 2252.53)
        -- [MISSING] Conveyor  was at (1197.19, 2664.62, 2269.52)
        workspace.Towers.ToOH.Obby:GetChildren()[561],
        -- [MISSING] ButtonPart  was at (1209.33, 2641.81, 2282.87)
        workspace.Towers.ToOH.Obby:GetChildren()[609],
        workspace.Towers.ToOH.Obby:GetChildren()[608],
        -- [MISSING] Conveyor  was at (1221.33, 2357.23, 2319.88)
        workspace.Towers.ToOH.Obby:GetChildren()[743],
        workspace.Towers.ToOH.Obby:GetChildren()[598],
        workspace.Towers.ToOH.Obby:GetChildren()[565],
        -- [MISSING] Part  was at (1214.33, 2375.58, 2308.37)
        -- [MISSING] Part  was at (1220.33, 2381.58, 2301.37)
        workspace.Towers.ToOH.Obby:GetChildren()[566],
        workspace.Towers.ToOH.Obby:GetChildren()[567],
        workspace.Towers.ToOH.Obby:GetChildren()[607],
        workspace.Towers.ToOH.Obby:GetChildren()[606],
        workspace.Towers.ToOH.Obby:GetChildren()[564],
        workspace.Towers.ToOH.Obby:GetChildren()[569],
        workspace.Towers.ToOH.Obby:GetChildren()[653],
        workspace.Towers.ToOH.Obby:GetChildren()[575],
        workspace.Towers.ToOH.Obby:GetChildren()[578],
        -- [MISSING] Motor  was at (1222.83, 2421.07, 2306.37)
        workspace.Towers.ToOH.Obby:GetChildren()[641],
        workspace.Towers.ToOH.Obby:GetChildren()[507],
        workspace.Towers.ToOH.Obby:GetChildren()[445],
        workspace.Towers.ToOH.Obby:GetChildren()[584],
        -- [MISSING] Part  was at (1207.33, 2546.62, 2319.37)
        workspace.Towers.ToOH.Obby:GetChildren()[56],
        workspace.Towers.ToOH.Obby:GetChildren()[592],
        workspace.Towers.ToOH.Obby:GetChildren()[593],
        workspace.Towers.ToOH.Obby:GetChildren()[599],
        workspace.Towers.ToOH.Obby:GetChildren()[601],
        workspace.Towers.ToOH.Obby:GetChildren()[605],
        -- [MISSING] Part  was at (1179.93, 2618.93, 2319.36)
        workspace.Towers.ToOH.Obby:GetChildren()[826],
        workspace.Towers.ToOH.Obby:GetChildren()[827],
        workspace.Towers.ToOH.Obby:GetChildren()[828],
        workspace.Towers.ToOH.Obby:GetChildren()[829],
        workspace.Towers.ToOH.Obby:GetChildren()[830],
        -- [MISSING] Part  was at (1147.33, 2625.62, 2282.36)
        workspace.Towers.ToOH.Obby:GetChildren()[832],
        workspace.Towers.ToOH.Obby:GetChildren()[831],
        workspace.Towers.ToOH.Obby:GetChildren()[835],
        workspace.Towers.ToOH.Obby:GetChildren()[838],
        workspace.Towers.ToOH.Obby:GetChildren()[839],
        -- [MISSING] Conveyor  was at (1126.60, 2631.11, 2319.04)
        -- [MISSING] Part  was at (1114.33, 2634.62, 2311.36)
        workspace.Towers.ToOH.Obby:GetChildren()[153],
        workspace.Towers.ToOH.Obby:GetChildren()[8]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[8]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[113],
        workspace.Towers.ToOH.Obby:GetChildren()[8]:FindFirstChild("Curve"):FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[8]:FindFirstChild("Curve"):FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[545],
        workspace.Towers.ToOH.Obby:GetChildren()[926],
        workspace.Towers.ToOH.Obby:GetChildren()[672],
        workspace.Towers.ToOH.Obby:GetChildren()[671],
        workspace.Towers.ToOH.Obby:GetChildren()[618],
        -- [MISSING] Part  was at (1044.28, 2677.07, 2304.35)
        workspace.Towers.ToOH.Obby:GetChildren()[619],
        workspace.Towers.ToOH.Obby:GetChildren()[623],
        workspace.Towers.ToOH.Obby:GetChildren()[9]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[9]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[629],
        workspace.Towers.ToOH.Obby:GetChildren()[626],
        workspace.Towers.ToOH.Obby:GetChildren()[627],
        workspace.Towers.ToOH.Obby:GetChildren()[622],
        -- [MISSING] Button  was at (1073.83, 2671.56, 2262.87)
        workspace.Towers.ToOH.Frame:GetChildren()[75],
        workspace.Towers.ToOH.Obby:GetChildren()[631],
        workspace.Towers.ToOH.Obby:GetChildren()[632],
        -- [MISSING] Part  was at (1108.75, 2677.10, 2259.37)
        -- [MISSING] Conveyor  was at (1126.74, 2674.56, 2259.37)
        -- [MISSING] Part  was at (1120.62, 2672.46, 2240.37)
        workspace.Towers.ToOH.Obby:GetChildren()[778],
        workspace.Towers.ToOH.Obby:GetChildren()[780],
        workspace.Towers.ToOH.Obby:GetChildren()[530],
        -- [MISSING] Motor  was at (1123.78, 2681.31, 2190.00)
        -- [MISSING] Motor  was at (1123.78, 2694.31, 2190.00)
        workspace.Towers.ToOH.Obby:GetChildren()[529],
        workspace.Towers.ToOH.Obby:GetChildren()[532],
        workspace.Towers.ToOH.Obby:GetChildren()[531],
        -- [MISSING] Part  was at (1138.33, 2701.72, 2222.52)
        -- [MISSING] Part  was at (1154.33, 2694.72, 2222.52)
        workspace.Towers.ToOH.Obby:GetChildren()[775],
        workspace.Towers.ToOH.Obby:GetChildren()[754],
        workspace.Towers.ToOH.Obby:GetChildren()[645],
        -- [MISSING] Part  was at (1166.83, 2702.56, 2237.88)
        -- [MISSING] Part  was at (1082.83, 2703.56, 2237.87)
        workspace.Towers.ToOH.Obby:GetChildren()[639],
        workspace.Towers.ToOH.Obby:GetChildren()[636],
        workspace.Towers.ToOH.Obby:GetChildren()[635],
        -- [MISSING] Part  was at (1083.14, 2710.60, 2199.97)
        workspace.Towers.ToOH.Obby:GetChildren()[776],
        workspace.Towers.ToOH.Obby:GetChildren()[753],
        -- [MISSING] Part  was at (1119.93, 2725.55, 2200.33)
        -- [MISSING] Part  was at (1130.93, 2721.55, 2204.33)
        -- [MISSING] Part  was at (1144.40, 2712.37, 2201.37)
        workspace.Towers.ToOH.Obby:GetChildren()[853],
        workspace.Towers.ToOH.Obby:GetChildren()[852],
        workspace.Towers.ToOH.Obby:GetChildren()[841],
        workspace.Towers.ToOH.Obby:GetChildren()[118],
        workspace.Towers.ToOH.Obby:GetChildren()[437],
        workspace.Towers.ToOH.Obby:GetChildren()[438],
        workspace.Towers.ToOH.Obby:GetChildren()[638],
        workspace.Towers.ToOH.Obby:GetChildren()[646],
        workspace.Towers.ToOH.Obby:GetChildren()[647],
        workspace.Towers.ToOH.Obby:GetChildren()[650],
        workspace.Towers.ToOH.Obby:GetChildren()[649],
        workspace.Towers.ToOH.Obby:GetChildren()[652],
        workspace.Towers.ToOH.Obby:GetChildren()[668],
        -- [MISSING] Part  was at (1159.32, 2764.55, 2177.37)
        workspace.Towers.ToOH.Obby:GetChildren()[800],
        workspace.Towers.ToOH.Obby:GetChildren()[681],
        workspace.Towers.ToOH.Obby:GetChildren()[673],
        workspace.Towers.ToOH.Obby:GetChildren()[674],
        workspace.Towers.ToOH.Obby:GetChildren()[854],
        workspace.Towers.ToOH.Obby:GetChildren()[675],
        workspace.Towers.ToOH.Obby:GetChildren()[670],
        workspace.Towers.ToOH.Obby:GetChildren()[676],
        workspace.Towers.ToOH.Obby:GetChildren()[677],
        workspace.Towers.ToOH.Obby:GetChildren()[680],
        workspace.Towers.ToOH.Obby:GetChildren()[679],
        workspace.Towers.ToOH.Obby:GetChildren()[758],
        workspace.Towers.ToOH.Obby:GetChildren()[682],
        workspace.Towers.ToOH.Obby:GetChildren()[683],
        workspace.Towers.ToOH.Obby:GetChildren()[702],
        workspace.Towers.ToOH.Obby:GetChildren()[692],
        workspace.Towers.ToOH.Obby:GetChildren()[694],
        workspace.Towers.ToOH.Obby:GetChildren()[698],
        workspace.Towers.ToOH.Obby:GetChildren()[662],
        workspace.Towers.ToOH.Obby:GetChildren()[678],
        workspace.Towers.ToOH.Obby:GetChildren()[701],
        workspace.Towers.ToOH.Obby:GetChildren()[684],
        workspace.Towers.ToOH.Obby:GetChildren()[706],
        workspace.Towers.ToOH.Obby:GetChildren()[708],
        workspace.Towers.ToOH.Obby:GetChildren()[709],
        workspace.Towers.ToOH.Obby:GetChildren()[712],
        workspace.Towers.ToOH.Obby:GetChildren()[717],
        workspace.Towers.ToOH.Obby:GetChildren()[704],
        workspace.Towers.ToOH.Obby:GetChildren()[720],
        workspace.Towers.ToOH.Obby:GetChildren()[719],
        workspace.Towers.ToOH.Obby:GetChildren()[721],
        workspace.Towers.ToOH.Obby:GetChildren()[722],
        workspace.Towers.ToOH.Obby:GetChildren()[723],
        workspace.Towers.ToOH.Obby:GetChildren()[724],
        workspace.Towers.ToOH.Obby:GetChildren()[726],
        workspace.Towers.ToOH.Obby:GetChildren()[729],
        workspace.Towers.ToOH.Obby:GetChildren()[730],
        workspace.Towers.ToOH.Obby:GetChildren()[733],
        workspace.Towers.ToOH.Obby:GetChildren()[731],
        workspace.Towers.ToOH.Obby:GetChildren()[742],
        -- [MISSING] Part  was at (1124.78, 2824.06, 2257.37)
        workspace.Towers.ToOH.Obby:GetChildren()[17],
        workspace.Towers.ToOH.Obby:GetChildren()[16],
        workspace.Towers.ToOH.Obby:GetChildren()[732],
        workspace.Towers.ToOH.Obby:GetChildren()[25],
        workspace.Towers.ToOH.Obby:GetChildren()[18],
        workspace.Towers.ToOH.Obby:GetChildren()[19],
        workspace.Towers.ToOH.Obby:GetChildren()[737],
        workspace.Towers.ToOH.Obby:GetChildren()[738],
        workspace.Towers.ToOH.Obby:GetChildren()[741],
        workspace.Towers.ToOH.Obby:GetChildren()[657],
        workspace.Towers.ToOH.Obby:GetChildren()[739],
        workspace.Towers.ToOH.Obby:GetChildren()[740],
        workspace.Towers.ToOH.Obby:GetChildren()[660],
        workspace.Towers.ToOH.Obby:GetChildren()[663],
        workspace.Towers.ToOH.Obby:GetChildren()[659],
        workspace.Towers.ToOH.Obby:GetChildren()[661],
        -- [MISSING] Conveyor  was at (1100.58, 2834.70, 2222.25)
        workspace.Towers.ToOH.Obby:GetChildren()[644],
        workspace.Towers.ToOH.Obby:GetChildren()[436],
        workspace.Towers.ToOH.Obby:GetChildren()[850],
        workspace.Towers.ToOH.Obby:GetChildren()[602],
        workspace.Towers.ToOH.Obby:GetChildren()[855],
        workspace.Towers.ToOH.Obby:GetChildren()[856],
        workspace.Towers.ToOH.Obby:GetChildren()[745],
        workspace.Towers.ToOH.Obby:GetChildren()[857],
        workspace.Towers.ToOH.Obby:GetChildren()[861],
        workspace.Towers.ToOH.Obby:GetChildren()[862],
        workspace.Towers.ToOH.Obby:GetChildren()[789],
        workspace.Towers.ToOH.Obby:GetChildren()[799],
        workspace.Towers.ToOH.Obby:GetChildren()[787],
        workspace.Towers.ToOH.Obby:GetChildren()[665],
        workspace.Towers.ToOH.Obby:GetChildren()[699],
        workspace.Towers.ToOH.Obby:GetChildren()[715],
        workspace.Towers.ToOH.Obby:GetChildren()[700],
        workspace.Towers.ToOH.Obby:GetChildren()[514],
        workspace.Towers.ToOH.Obby:GetChildren()[785],
        workspace.Towers.ToOH.Obby:GetChildren()[666],
        workspace.Towers.ToOH.Obby:GetChildren()[685],
        workspace.Towers.ToOH.Obby:GetChildren()[713],
        workspace.Towers.ToOH.Obby:GetChildren()[716],
        -- [MISSING] Part  was at (1166.08, 2868.55, 2181.61)
        -- [MISSING] Part  was at (1163.99, 2869.07, 2183.70)
        workspace.Towers.ToOH.Obby:GetChildren()[744],
        workspace.Towers.ToOH.Obby:GetChildren()[750],
        workspace.Towers.ToOH.Obby:GetChildren()[748],
        -- [MISSING] Conveyor  was at (1141.63, 2876.57, 2218.09)
        workspace.Towers.ToOH.Obby:GetChildren()[749],
        workspace.Towers.ToOH.Obby:GetChildren()[863],
        workspace.Towers.ToOH.Obby:GetChildren()[73],
        -- [MISSING] Part  was at (1126.99, 2888.31, 2220.71)
        workspace.Towers.ToOH.Obby:GetChildren()[768],
        workspace.Towers.ToOH.Obby:GetChildren()[784],
        workspace.Towers.ToOH.Obby:GetChildren()[781],
        workspace.Towers.ToOH.Obby:GetChildren()[760],
        workspace.Towers.ToOH.Obby:GetChildren()[774],
        workspace.Towers.ToOH.Obby:GetChildren()[792],
        workspace.Towers.ToOH.Obby:GetChildren()[71],
        workspace.Towers.ToOH.Obby:GetChildren()[764],
        -- [MISSING] Part  was at (1104.36, 2890.24, 2185.49)
        workspace.Towers.ToOH.Obby:GetChildren()[874],
        workspace.Towers.ToOH.Obby:GetChildren()[868],
        workspace.Towers.ToOH.Obby:GetChildren()[766],
        workspace.Towers.ToOH.Obby:GetChildren()[872],
        workspace.Towers.ToOH.Obby:GetChildren()[870],
        workspace.Towers.ToOH.Obby:GetChildren()[871],
        workspace.Towers.ToOH.Obby:GetChildren()[794],
        workspace.Towers.ToOH.Obby:GetChildren()[783],
        workspace.Towers.ToOH.Obby:GetChildren()[873],
        workspace.Towers.ToOH.Obby:GetChildren()[67],
        -- [MISSING] Part  was at (1160.64, 2910.76, 2199.45)
        -- [MISSING] Part  was at (1160.64, 2912.23, 2202.62)
        workspace.Towers.ToOH.Obby:GetChildren()[767],
        workspace.Towers.ToOH.Obby:GetChildren()[782],
        -- [MISSING] Conveyor  was at (1171.33, 2920.28, 2249.47)
        -- [MISSING] Conveyor  was at (1171.33, 2899.24, 2257.63)
        workspace.Towers.ToOH.Obby:GetChildren()[139],
        -- [MISSING] Part  was at (1161.33, 2882.56, 2269.38)
        workspace.Towers.ToOH.Obby:GetChildren()[751],
        -- [MISSING] Part  was at (1144.83, 2871.34, 2269.87)
        workspace.Towers.ToOH.Obby:GetChildren()[876],
        workspace.Towers.ToOH.Obby:GetChildren()[865],
        workspace.Towers.ToOH.Obby:GetChildren()[879],
        workspace.Towers.ToOH.Obby:GetChildren()[773],
        workspace.Towers.ToOH.Obby:GetChildren()[883],
        workspace.Towers.ToOH.Obby:GetChildren()[890],
        workspace.Towers.ToOH.Obby:GetChildren()[893],
        workspace.Towers.ToOH.Obby:GetChildren()[892],
        workspace.Towers.ToOH.Obby:GetChildren()[889],
        -- [MISSING] Part  was at (1113.83, 2924.61, 2269.87)
        -- [MISSING] Part  was at (1105.83, 2914.61, 2269.87)
        workspace.Towers.ToOH.Obby:GetChildren()[887],
        workspace.Towers.ToOH.Obby:GetChildren()[562],
        -- [MISSING] Part  was at (1082.83, 2927.61, 2269.88)
        workspace.Towers.ToOH.Obby:GetChildren()[798],
        workspace.Towers.ToOH.Obby:GetChildren()[932],
        workspace.Towers.ToOH.Obby:GetChildren()[797],
        workspace.Towers.ToOH.Obby:GetChildren()[937],
        workspace.Towers.ToOH.Obby:GetChildren()[802],
        workspace.Towers.ToOH.Obby:GetChildren()[12]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[12]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[11]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[11]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Frame:GetChildren()[58],
        workspace.Towers.ToOH.Obby:GetChildren()[14]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[13]:FindFirstChild("Part"),
        workspace.Towers.ToOH.Obby:GetChildren()[804],
        workspace.Towers.ToOH.Obby:GetChildren()[807],
        workspace.Towers.ToOH.Obby:GetChildren()[810],
        -- [MISSING] Conveyor  was at (1142.83, 2971.56, 2211.88)
        workspace.Towers.ToOH.Obby:GetChildren()[811],
        workspace.Towers.ToOH.Obby:GetChildren()[812],
        workspace.Towers.ToOH.Obby:GetChildren()[813],
        -- [MISSING] Conveyor  was at (1157.05, 2978.56, 2228.83)
        workspace.Towers.ToOH.Obby:GetChildren()[816],
        workspace.Towers.ToOH.Obby:GetChildren()[96],
        workspace.Towers.ToOH.Obby:GetChildren()[817],
        workspace.Towers.ToOH.Obby:GetChildren()[819],
        workspace.Towers.ToOH.Obby:GetChildren()[821],
        workspace.Towers.ToOH.Obby:GetChildren()[822],
        workspace.Towers.ToOH.Obby:GetChildren()[746],
        workspace.Towers.ToOH.Obby:GetChildren()[825],
        workspace.Towers.ToOH.Obby:GetChildren()[373],
        workspace.Towers.ToOH.Obby:GetChildren()[503],
        workspace.Towers.ToOH.Obby:GetChildren()[523],
        -- [MISSING] Motor  was at (1105.62, 3002.57, 2232.08)
        -- [MISSING] Part  was at (1105.62, 3011.56, 2232.08)
        workspace.Towers.ToOH.Obby:GetChildren()[611],
        workspace.Towers.ToOH.Obby:GetChildren()[654],
        -- [MISSING] Part  was at (1100.02, 3027.57, 2211.30)
        workspace.Towers.ToOH.Obby:GetChildren()[140],
        -- [MISSING] Part  was at (1105.87, 3025.57, 2196.30)
        -- [MISSING] Part  was at (1108.76, 3025.57, 2195.52)
        workspace.Towers.ToOH.Obby:GetChildren()[900],
        workspace.Towers.ToOH.Obby:GetChildren()[895],
        workspace.Towers.ToOH.Obby:GetChildren()[894],
        workspace.Towers.ToOH.Obby:GetChildren()[897],
        workspace.Towers.ToOH.Obby:GetChildren()[901],
        workspace.Towers.ToOH.Obby:GetChildren()[902],
        workspace.Towers.ToOH.Obby:GetChildren()[899],
        workspace.Towers.ToOH.Obby:GetChildren()[905],
        -- [MISSING] Part  was at (1166.16, 3024.06, 2247.20)
        workspace.Towers.ToOH.Obby:GetChildren()[906],
        -- [MISSING] Part  was at (1136.50, 3024.06, 2241.55)
        workspace.Towers.ToOH.Obby:GetChildren()[907],
        -- [MISSING] Part  was at (1139.33, 3022.61, 2265.38)
        workspace.Towers.ToOH.Obby:GetChildren()[909],
        workspace.Towers.ToOH.Obby:GetChildren()[72],
        -- [MISSING] Part  was at (1151.83, 3052.56, 2265.38)
        -- [MISSING] Part  was at (1155.33, 3052.61, 2265.38)
        workspace.Towers.ToOH.Obby:GetChildren()[911],
        workspace.Towers.ToOH.Obby:GetChildren()[597],
        workspace.Towers.ToOH.Obby:GetChildren()[912],
        workspace.Towers.ToOH.Obby:GetChildren()[604],
        workspace.Towers.ToOH.Obby:GetChildren()[788],
        workspace.Towers.ToOH.Obby:GetChildren()[70],
        workspace.Towers.ToOH.Obby:GetChildren()[603],
        -- [MISSING] Part  was at (1115.33, 3075.57, 2246.38)
        -- [MISSING] Part  was at (1112.33, 3075.57, 2246.38)
        -- [MISSING] Part  was at (1088.33, 3076.61, 2238.87)
        workspace.Towers.ToOH.Obby:GetChildren()[772],
        -- [MISSING] Conveyor  was at (1088.33, 3097.56, 2204.37)
        workspace.Towers.ToOH.Obby:GetChildren()[21],
        workspace.Towers.ToOH.Obby:GetChildren()[69],
        -- [MISSING] Part  was at (1082.07, 3070.56, 2202.95)
        -- [MISSING] Part  was at (1084.96, 3070.56, 2203.73)
        workspace.Towers.ToOH.Obby:GetChildren()[934],
        -- [MISSING] Part  was at (1162.06, 3066.06, 2213.51)
        workspace.Towers.ToOH.Obby:GetChildren()[908],
        workspace.Towers.ToOH.Obby:GetChildren()[916],
        workspace.Towers.ToOH.Obby:GetChildren()[915],
        -- [MISSING] Conveyor  was at (1158.33, 3070.56, 2194.36)
        workspace.Towers.ToOH.Obby:GetChildren()[931],
        workspace.Towers.ToOH.Obby:GetChildren()[936],
        workspace.Towers.ToOH.Obby:GetChildren()[933],
        workspace.Towers.ToOH.Obby:GetChildren()[928],
        -- [MISSING] Part  was at (1120.33, 3068.61, 2188.87)
        workspace.Towers.ToOH.Obby:GetChildren()[23],
        workspace.Towers.ToOH.Obby:GetChildren()[27],
        workspace.Towers.ToOH.Obby:GetChildren()[29],
        workspace.Towers.ToOH.Obby:GetChildren()[30],
        workspace.Towers.ToOH.Obby:GetChildren()[32],
        workspace.Towers.ToOH.Obby:GetChildren()[33],
        -- [MISSING] Part  was at (1124.33, 3106.56, 2227.88)
        workspace.Towers.ToOH.WinPad
    }
end
