return function()
    return {
        workspace.Towers.ToA.Obby:GetChildren()[14], --F1
        workspace.Towers.ToA.Obby:GetChildren()[12],
        workspace.Towers.ToA.Obby:GetChildren()[59],
        workspace.Towers.ToA.Obby:GetChildren()[60],
        workspace.ClientParts.DistanceCulling:GetChildren()[13].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[63],
        workspace.Towers.ToA.Obby:GetChildren()[62],
        workspace.Towers.ToA.Obby:GetChildren()[68],
        workspace.Towers.ToA.Obby:GetChildren()[71],
        workspace.Towers.ToA.Obby:GetChildren()[69],
        workspace.Towers.ToA.Obby:GetChildren()[67],
        workspace.Towers.ToA.Obby:GetChildren()[77],
        workspace.Towers.ToA.Obby:GetChildren()[75],
        workspace.Towers.ToA.Obby:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[84],
        workspace.ClientParts.DistanceCulling:GetChildren()[10].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[11].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[90],
        workspace.Towers.ToA.Obby:GetChildren()[66],
        workspace.ClientParts:GetChildren()[79],
        workspace.ClientParts:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[97],
        workspace.Towers.ToA.Obby:GetChildren()[92],
        workspace.Towers.ToA.Obby:GetChildren()[98],
        workspace.Towers.ToA.Obby:GetChildren()[93],
        workspace.Towers.ToA.Obby:GetChildren()[91],
        workspace.Towers.ToA.Obby:GetChildren()[100],
        workspace.Towers.ToA.Obby:GetChildren()[101],
        workspace.Towers.ToA.Obby:GetChildren()[99],
        workspace.Towers.ToA.Obby:GetChildren()[111],
        workspace.Towers.ToA.Obby:GetChildren()[112],
        workspace.ClientParts:GetChildren()[81],
        workspace.ClientParts:GetChildren()[82],
        workspace.ClientParts:GetChildren()[83],
        workspace.Towers.ToA.Obby:GetChildren()[105],
        workspace.Towers.ToA.Obby:GetChildren()[113],
        workspace.Towers.ToA.Obby:GetChildren()[115],
        workspace.Towers.ToA.Obby:GetChildren()[116],
        workspace.Towers.ToA.Obby:GetChildren()[120],
        workspace.ClientParts.DistanceCulling:GetChildren()[14].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[15].Platform,
        workspace.ClientParts:GetChildren()[84],
        workspace.Towers.ToA.Obby:GetChildren()[121],
        workspace.Towers.ToA.Obby:GetChildren()[122],
        workspace.Towers.ToA.Obby:GetChildren()[124],
        workspace.Towers.ToA.Obby:GetChildren()[128],
        workspace.Towers.ToA.Obby:GetChildren()[129],
        workspace.Towers.ToA.Obby:GetChildren()[130],
        workspace.Towers.ToA.Obby:GetChildren()[131],
        workspace.Towers.ToA.Obby:GetChildren()[72],
        workspace.Towers.ToA.Obby:GetChildren()[20],
        workspace.Towers.ToA.Obby:GetChildren()[132],
        workspace.Towers.ToA.Obby:GetChildren()[133],
        workspace.ClientParts.DistanceCulling:GetChildren()[17].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[138],
        workspace.Towers.ToA.Obby:GetChildren()[140],
        workspace.Towers.ToA.Obby:GetChildren()[155],
        workspace.Towers.ToA.Obby:GetChildren()[153],
        workspace.Towers.ToA.Obby:GetChildren()[143], --F2
        workspace.Towers.ToA.Obby:GetChildren()[168],
        workspace.Towers.ToA.Obby:GetChildren()[149],
        workspace.Towers.ToA.Obby:GetChildren()[169],
        workspace.Towers.ToA.Obby:GetChildren()[170],
        workspace.Towers.ToA.Obby:GetChildren()[171],
        workspace.Towers.ToA.Obby:GetChildren()[174],
        workspace.Towers.ToA.Obby:GetChildren()[172],
        workspace.Towers.ToA.Obby:GetChildren()[176],
        workspace.Towers.ToA.Obby:GetChildren()[177],
        workspace.Towers.ToA.Obby:GetChildren()[179],
        workspace.ClientParts:GetChildren()[85],
        workspace.ClientParts:GetChildren()[86],
        workspace.Towers.ToA.Obby:GetChildren()[187],
        workspace.Towers.ToA.Obby:GetChildren()[186],
        workspace.ClientParts.ParticleParts:GetChildren()[11],
        workspace.Towers.ToA.Obby:GetChildren()[1516],
        workspace.ClientParts.ParticleParts.Part,
        workspace.ClientParts["Rainbow Button 1"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[10],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[7],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[3],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[14],
        workspace.Towers.ToA.Obby:GetChildren()[206],
        workspace.Towers.ToA.Obby:GetChildren()[207],
        workspace.Towers.ToA.Obby:GetChildren()[210],
        workspace.ClientParts.DistanceCulling:GetChildren()[21].Parts:GetChildren()[2],
        workspace.Towers.ToA.Obby:GetChildren()[213],
        workspace.Towers.ToA.Obby:GetChildren()[215],
        workspace.Towers.ToA.Obby:GetChildren()[214],
        workspace.Towers.ToA.Obby:GetChildren()[54],
        workspace.Towers.ToA.Obby:GetChildren()[216],
        workspace.Towers.ToA.Obby:GetChildren()[218],
        workspace.Towers.ToA.Obby:GetChildren()[219],
        workspace.ClientParts.DistanceCulling:GetChildren()[23].Platform,
        workspace.ClientParts:GetChildren()[89],
        workspace.ClientParts:GetChildren()[90],
        workspace.ClientParts:GetChildren()[118],
        workspace.Towers.ToA.Obby:GetChildren()[223],
        workspace.Towers.ToA.Obby:GetChildren()[235],
        workspace.Towers.ToA.Obby:GetChildren()[230],
        workspace.Towers.ToA.Obby:GetChildren()[1522],
        workspace.Towers.ToA.Obby:GetChildren()[239],
        workspace.Towers.ToA.Obby:GetChildren()[240],
        workspace.ClientParts.DistanceCulling:GetChildren()[24].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[24]:GetChildren()[2],
        workspace.ClientParts.DistanceCulling:GetChildren()[24]:GetChildren()[3],
        workspace.Towers.ToA.Obby:GetChildren()[241],
        workspace.Towers.ToA.Obby:GetChildren()[243],
        workspace.Towers.ToA.Obby:GetChildren()[246],
        workspace.Towers.ToA.Obby:GetChildren()[245],
        workspace.Towers.ToA.Obby:GetChildren()[248], --F3
        workspace.Towers.ToA.Obby:GetChildren()[247],
        workspace.Towers.ToA.Obby:GetChildren()[255],
        workspace.Towers.ToA.Obby:GetChildren()[254],
        workspace.Towers.ToA.Obby:GetChildren()[252],
        workspace.Towers.ToA.Obby:GetChildren()[253],
        workspace.Towers.ToA.Obby:GetChildren()[257],
        workspace.ClientParts.DistanceCulling:GetChildren()[26].Parts:GetChildren()[2],
        workspace.Towers.ToA.Obby:GetChildren()[258],
        workspace.Towers.ToA.Obby:GetChildren()[259],
        workspace.Towers.ToA.Obby:GetChildren()[261],
        workspace.Towers.ToA.Obby:GetChildren()[262],
        workspace.Towers.ToA.Obby:GetChildren()[263],
        workspace.Towers.ToA.Obby:GetChildren()[266],
        workspace.Towers.ToA.Obby:GetChildren()[268],
        workspace.Towers.ToA.Obby:GetChildren()[269],
        workspace.ClientParts:GetChildren()[93],
        workspace.ClientParts:GetChildren()[94],
        workspace.Towers.ToA.Obby:GetChildren()[275],
        workspace.Towers.ToA.Obby:GetChildren()[274],
        workspace.ClientParts:GetChildren()[27].Pushbox["Rope Swing Platform"].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[280],
        workspace.Towers.ToA.Obby:GetChildren()[281],
        workspace.Towers.ToA.Obby:GetChildren()[282],
        workspace.Towers.ToA.Obby:GetChildren()[288],
        workspace.Towers.ToA.Obby:GetChildren()[277],
        workspace.Towers.ToA.Obby:GetChildren()[278],
        workspace.Towers.ToA.Obby:GetChildren()[283],
        workspace.Towers.ToA.Obby:GetChildren()[286],
        workspace.Towers.ToA.Obby:GetChildren()[289],
        workspace.Towers.ToA.Obby:GetChildren()[329],
        workspace.Towers.ToA.Obby:GetChildren()[284],
        workspace.Towers.ToA.Obby:GetChildren()[290],
        workspace.Towers.ToA.Obby:GetChildren()[307],
        workspace.Towers.ToA.Obby:GetChildren()[308],
        workspace.ClientParts:GetChildren()[29].Part,
        workspace.ClientParts:GetChildren()[29].Primary,
        workspace.ClientParts:GetChildren()[95],
        workspace.ClientParts:GetChildren()[96],
        workspace.Towers.ToA.Obby:GetChildren()[294],
        workspace.Towers.ToA.Obby:GetChildren()[316],
        workspace.Towers.ToA.Obby:GetChildren()[328],
        workspace.Towers.ToA.Obby:GetChildren()[325],
        workspace.Towers.ToA.Obby:GetChildren()[327],
        workspace.Towers.ToA.Obby:GetChildren()[326],
        workspace.Towers.ToA.Obby:GetChildren()[321],
        workspace.Towers.ToA.Obby:GetChildren()[324],
        workspace.Towers.ToA.Obby:GetChildren()[296],
        workspace.Towers.ToA.Obby:GetChildren()[319],
        workspace.Towers.ToA.Obby:GetChildren()[296],
        workspace.Towers.ToA.Obby:GetChildren()[299],
        workspace.Towers.ToA.Obby:GetChildren()[302],
        workspace.Towers.ToA.Obby:GetChildren()[298],
        workspace.ClientParts["Rainbow Button 2"].Button.Part,
        workspace.ClientParts["Rainbow Button 2"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 2"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[3],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[5],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[6],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[7],
        workspace.ClientParts:GetChildren()[97],
        workspace.ClientParts:GetChildren()[98],
        workspace.ClientParts:GetChildren()[99],
        workspace.Towers.ToA.Obby:GetChildren()[352],
        workspace.Towers.ToA.Obby:GetChildren()[354],
        workspace.Towers.ToA.Obby:GetChildren()[355],
        workspace.Towers.ToA.Obby:GetChildren()[370],
        workspace.Towers.ToA.Obby:GetChildren()[356],
        workspace.Towers.ToA.Obby:GetChildren()[369],
        workspace.Towers.ToA.Obby:GetChildren()[357],
        workspace.Towers.ToA.Obby:GetChildren()[358],
        workspace.Towers.ToA.Obby:GetChildren()[360],
        workspace.Towers.ToA.Obby:GetChildren()[362],
        workspace.Towers.ToA.Obby:GetChildren()[364], --F4
        workspace.Towers.ToA.Obby:GetChildren()[342],
        workspace.ClientParts:GetChildren()[103],
        workspace.Towers.ToA.Obby:GetChildren()[335],
        workspace.Towers.ToA.Obby:GetChildren()[431],
        workspace.Towers.ToA.Obby:GetChildren()[429],
        workspace.Towers.ToA.Obby:GetChildren()[430],
        workspace.Towers.ToA.Obby:GetChildren()[427],
        workspace.Towers.ToA.Obby:GetChildren()[440],
        workspace.Towers.ToA.Obby:GetChildren()[441],
        workspace.ClientParts:GetChildren()[108],
        workspace.Towers.ToA.Obby:GetChildren()[426],
        workspace.Towers.ToA.Obby:GetChildren()[423],
        workspace.Towers.ToA.Obby:GetChildren()[462],
        workspace.Towers.ToA.Obby:GetChildren()[464],
        workspace.Towers.ToA.Obby:GetChildren()[465],
        workspace.ClientParts:GetChildren()[113],
        workspace.Towers.ToA.Obby:GetChildren()[477],
        workspace.Towers.ToA.Obby:GetChildren()[491],
        workspace.Towers.ToA.Obby:GetChildren()[474],
        workspace.ClientParts["Rainbow Button 3"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[6],
        workspace.ClientParts.ParticleParts["Rainbow Button 3"].PushboxSpawnButton.Pushbox["Rope Swing Platform"].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[8],
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[10],
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]["Rope Swing Platform"].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[3].Platform,
        workspace.ClientParts:GetChildren()[116],
        workspace.ClientParts:GetChildren()[117],
        workspace.Towers.ToA.Obby:GetChildren()[502],
        workspace.Towers.ToA.Obby:GetChildren()[503],
        workspace.Towers.ToA.Obby:GetChildren()[508],
        workspace.Towers.ToA.Obby:GetChildren()[509],
        workspace.Towers.ToA.Obby:GetChildren()[526],
        workspace.Towers.ToA.Obby:GetChildren()[525],
        workspace.Towers.ToA.Obby:GetChildren()[524],
        workspace.Towers.ToA.Obby:GetChildren()[527],
        workspace.Towers.ToA.Obby:GetChildren()[530],
        workspace.Towers.ToA.Obby:GetChildren()[529],
        workspace.Towers.ToA.Obby:GetChildren()[1494],
        workspace.Towers.ToA.Obby:GetChildren()[510],
        workspace.Towers.ToA.Obby:GetChildren()[534],
        workspace.Towers.ToA.Obby:GetChildren()[532],
        workspace.Towers.ToA.Obby:GetChildren()[531],
        workspace.ClientParts.DistanceCulling:GetChildren()[27].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[2],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[6],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[8],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[9],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[7],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[3],
        workspace.Towers.ToA.Obby:GetChildren()[536]
        
        
        
        
        

    }
end
