return function()
    return {
        workspace.Towers.ToA.Obby:GetChildren()[14], --F1
        workspace.Towers.ToA.Obby:GetChildren()[12],
        workspace.Towers.ToA.Obby:GetChildren()[59],
        workspace.Towers.ToA.Obby:GetChildren()[60],
        workspace.ClientParts.DistanceCulling:GetChildren()[13].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[63],
        workspace.Towers.ToA.Obby:GetChildren()[62],
        workspace.Towers.ToA.Obby:GetChildren()[68],
        workspace.Towers.ToA.Obby:GetChildren()[71],
        workspace.Towers.ToA.Obby:GetChildren()[69],
        workspace.Towers.ToA.Obby:GetChildren()[67],
        workspace.Towers.ToA.Obby:GetChildren()[77],
        workspace.Towers.ToA.Obby:GetChildren()[75],
        workspace.Towers.ToA.Obby:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[84],
        workspace.ClientParts.DistanceCulling:GetChildren()[10].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[11].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[90],
        workspace.Towers.ToA.Obby:GetChildren()[66],
        workspace.ClientParts:GetChildren()[79],
        workspace.ClientParts:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[97],
        workspace.Towers.ToA.Obby:GetChildren()[92],
        workspace.Towers.ToA.Obby:GetChildren()[98],
        workspace.Towers.ToA.Obby:GetChildren()[93],
        workspace.Towers.ToA.Obby:GetChildren()[91],
        workspace.Towers.ToA.Obby:GetChildren()[100],
        workspace.Towers.ToA.Obby:GetChildren()[101],
        workspace.Towers.ToA.Obby:GetChildren()[99],
        workspace.Towers.ToA.Obby:GetChildren()[111],
        workspace.Towers.ToA.Obby:GetChildren()[112],
        workspace.ClientParts:GetChildren()[81],
        workspace.ClientParts:GetChildren()[82],
        workspace.ClientParts:GetChildren()[83],
        workspace.Towers.ToA.Obby:GetChildren()[105],
        workspace.Towers.ToA.Obby:GetChildren()[113],
        workspace.Towers.ToA.Obby:GetChildren()[115],
        workspace.Towers.ToA.Obby:GetChildren()[116],
        workspace.Towers.ToA.Obby:GetChildren()[120],
        workspace.ClientParts.DistanceCulling:GetChildren()[14].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[15].Platform,
        workspace.ClientParts:GetChildren()[84],
        workspace.Towers.ToA.Obby:GetChildren()[121],
        workspace.Towers.ToA.Obby:GetChildren()[122],
        workspace.Towers.ToA.Obby:GetChildren()[124],
        workspace.Towers.ToA.Obby:GetChildren()[128],
        workspace.Towers.ToA.Obby:GetChildren()[129],
        workspace.Towers.ToA.Obby:GetChildren()[130],
        workspace.Towers.ToA.Obby:GetChildren()[131],
        workspace.Towers.ToA.Obby:GetChildren()[72],
        workspace.Towers.ToA.Obby:GetChildren()[20],
        workspace.Towers.ToA.Obby:GetChildren()[132],
        workspace.Towers.ToA.Obby:GetChildren()[133],
        workspace.ClientParts.DistanceCulling:GetChildren()[17].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[138],
        workspace.Towers.ToA.Obby:GetChildren()[140],
        workspace.Towers.ToA.Obby:GetChildren()[155],
        workspace.Towers.ToA.Obby:GetChildren()[153],
        workspace.Towers.ToA.Obby:GetChildren()[143], --F2
        workspace.Towers.ToA.Obby:GetChildren()[168],
        workspace.Towers.ToA.Obby:GetChildren()[149],
        workspace.Towers.ToA.Obby:GetChildren()[169],
        workspace.Towers.ToA.Obby:GetChildren()[170],
        workspace.Towers.ToA.Obby:GetChildren()[171],
        workspace.Towers.ToA.Obby:GetChildren()[174],
        workspace.Towers.ToA.Obby:GetChildren()[172],
        workspace.Towers.ToA.Obby:GetChildren()[176],
        workspace.Towers.ToA.Obby:GetChildren()[177],
        workspace.Towers.ToA.Obby:GetChildren()[179],
        workspace.ClientParts:GetChildren()[85],
        workspace.ClientParts:GetChildren()[86],
        workspace.Towers.ToA.Obby:GetChildren()[187],
        workspace.Towers.ToA.Obby:GetChildren()[186],
        workspace.ClientParts.ParticleParts:GetChildren()[11],
        workspace.Towers.ToA.Obby:GetChildren()[1516],
        workspace.ClientParts.ParticleParts.Part,
        workspace.ClientParts["Rainbow Button 1"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[10],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[7],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[3],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[14],
        workspace.Towers.ToA.Obby:GetChildren()[206],
        workspace.Towers.ToA.Obby:GetChildren()[207],
        workspace.Towers.ToA.Obby:GetChildren()[210],
        workspace.ClientParts.DistanceCulling:GetChildren()[21].Parts:GetChildren()[2],
        workspace.Towers.ToA.Obby:GetChildren()[213],
        workspace.Towers.ToA.Obby:GetChildren()[215],
        workspace.Towers.ToA.Obby:GetChildren()[214],
        workspace.Towers.ToA.Obby:GetChildren()[54],
        workspace.Towers.ToA.Obby:GetChildren()[216],
        workspace.Towers.ToA.Obby:GetChildren()[218],
        workspace.Towers.ToA.Obby:GetChildren()[219],
        workspace.ClientParts.DistanceCulling:GetChildren()[23].Platform,
        workspace.ClientParts:GetChildren()[89],
        workspace.ClientParts:GetChildren()[90],
        workspace.ClientParts:GetChildren()[118],
        workspace.Towers.ToA.Obby:GetChildren()[223],
        workspace.Towers.ToA.Obby:GetChildren()[235],
        workspace.Towers.ToA.Obby:GetChildren()[230],
        workspace.Towers.ToA.Obby:GetChildren()[1522],
        workspace.Towers.ToA.Obby:GetChildren()[239],
        workspace.Towers.ToA.Obby:GetChildren()[240],
        workspace.ClientParts.DistanceCulling:GetChildren()[24].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[24]:GetChildren()[2],
        workspace.ClientParts.DistanceCulling:GetChildren()[24]:GetChildren()[3],
        workspace.Towers.ToA.Obby:GetChildren()[241],
        workspace.Towers.ToA.Obby:GetChildren()[243],
        workspace.Towers.ToA.Obby:GetChildren()[246],
        workspace.Towers.ToA.Obby:GetChildren()[245],
        workspace.Towers.ToA.Obby:GetChildren()[248]
        
        
        
        

    }
end
