return function()
    return {
        workspace.Towers.ToH.Obby:GetChildren()[844],
        workspace.Towers.ToH.Obby:GetChildren()[849],
        workspace.Towers.ToH.Obby:GetChildren()[843],
        workspace.Towers.ToH.Obby:GetChildren()[851],
        workspace.Towers.ToH.Obby:GetChildren()[848],
        workspace.Towers.ToH.Obby:GetChildren()[854],
        workspace.Towers.ToH.Obby:GetChildren()[865],
        workspace.Towers.ToH.Obby:GetChildren()[867],
        workspace.Towers.ToH.Obby:GetChildren()[508],
        workspace.Towers.ToH.Obby:GetChildren()[532],
        workspace.Towers.ToH.Obby:GetChildren()[527],
        workspace.Towers.ToH.Obby:GetChildren()[504],
        workspace.Towers.ToH.Obby:GetChildren()[502],
        workspace.Towers.ToH.Obby:GetChildren()[554], --F2
        workspace.Towers.ToH.Obby:GetChildren()[513],
        workspace.Towers.ToH.Obby:GetChildren()[62],
        workspace.Towers.ToH.Obby:GetChildren()[586],
        workspace.Towers.ToH.Obby:GetChildren()[533],
        workspace.Towers.ToH.Obby:GetChildren()[541],
        workspace.Towers.ToH.Obby:GetChildren()[581],
        workspace.Towers.ToH.Obby:GetChildren()[80],
        workspace.Towers.ToH.Obby:GetChildren()[546],
        workspace.Towers.ToH.Obby:GetChildren()[66],
        workspace.Towers.ToH.Obby:GetChildren()[149], --F3
        workspace.Towers.ToH.Obby:GetChildren()[105],
        workspace.Towers.ToH.Obby:GetChildren()[25],
        workspace.Towers.ToH.Obby:GetChildren()[88],
        workspace.Towers.ToH.Obby:GetChildren()[480],
        workspace.Towers.ToH.Obby:GetChildren()[77],
        workspace.Towers.ToH.Obby:GetChildren()[116],
        workspace.Towers.ToH.Obby:GetChildren()[117],
        workspace.Towers.ToH.Obby:GetChildren()[118],
        workspace.Towers.ToH.Obby:GetChildren()[154],
        workspace.Towers.ToH.Obby:GetChildren()[181],
        workspace.Towers.ToH.Obby:GetChildren()[164],
        workspace.Towers.ToH.Obby:GetChildren()[114],
        workspace.Towers.ToH.Obby:GetChildren()[95],
        workspace.Towers.ToH.Obby:GetChildren()[157],
        workspace.Towers.ToH.Obby:GetChildren()[90],
        workspace.Towers.ToH.Obby:GetChildren()[97],
        workspace.Towers.ToH.Obby:GetChildren()[171],
        workspace.Towers.ToH.Obby:GetChildren()[180], --F4
        workspace.Towers.ToH.Obby:GetChildren()[92],
        workspace.Towers.ToH.Obby:GetChildren()[188],
        workspace.Towers.ToH.Obby:GetChildren()[102],
        workspace.Towers.ToH.Obby:GetChildren()[100],
        workspace.Towers.ToH.Obby:GetChildren()[183],
        workspace.Towers.ToH.Obby:GetChildren()[193],
        workspace.Towers.ToH.Obby:GetChildren()[479],
        workspace.Towers.ToH.Obby:GetChildren()[93],
        workspace.Towers.ToH.Obby:GetChildren()[65],
        workspace.Towers.ToH.Obby:GetChildren()[113],
        workspace.Towers.ToH.Obby:GetChildren()[108],
        workspace.Towers.ToH.Obby:GetChildren()[156],
        workspace.Towers.ToH.Obby:GetChildren()[155],
        workspace.Towers.ToH.Obby:GetChildren()[242],
        workspace.Towers.ToH.Obby:GetChildren()[798],
        workspace.Towers.ToH.Obby:GetChildren()[799],
        workspace.Towers.ToH.Obby:GetChildren()[476],
        workspace.Towers.ToH.Obby:GetChildren()[235], --F5
        workspace.Towers.ToH.Obby:GetChildren()[243],
        workspace.Towers.ToH.Obby:GetChildren()[252],
        workspace.Towers.ToH.Obby:GetChildren()[194],
        workspace.Towers.ToH.Obby:GetChildren()[265],
        workspace.Towers.ToH.Obby:GetChildren()[182],
        workspace.Towers.ToH.Obby:GetChildren()[192],
        workspace.Towers.ToH.Obby:GetChildren()[783],
        workspace.Towers.ToH.Obby:GetChildren()[789],
        workspace.Towers.ToH.Obby:GetChildren()[236],
        workspace.Towers.ToH.Obby:GetChildren()[809],
        workspace.Towers.ToH.Obby:GetChildren()[786],
        workspace.Towers.ToH.Obby:GetChildren()[271],
        workspace.ClientParts:GetChildren()[28].Platform,
        workspace.ClientParts:GetChildren()[63].Platform,
        workspace.ClientParts:GetChildren()[34].Platform,
        workspace.Towers.ToH.Obby:GetChildren()[206], --F6
        workspace.Towers.ToH.Obby:GetChildren()[266],
        workspace.Towers.ToH.Obby:GetChildren()[276],
        workspace.Towers.ToH.Obby:GetChildren()[269],
        workspace.Towers.ToH.Obby:GetChildren()[131],
        workspace.Towers.ToH.Obby.Conveyor,
        workspace.Towers.ToH.Obby:GetChildren()[224],
        workspace.Towers.ToH.Obby:GetChildren()[141],
        workspace.Towers.ToH.Obby:GetChildren()[205],
        workspace.Towers.ToH.Obby:GetChildren()[139],
        workspace.Towers.ToH.Obby:GetChildren()[145],
        workspace.Towers.ToH.Obby:GetChildren()[207],
        workspace.Towers.ToH.Obby:GetChildren()[48],
        workspace.Towers.ToH.Obby:GetChildren()[50],
        workspace.Towers.ToH.Obby:GetChildren()[43],
        workspace.Towers.ToH.Obby:GetChildren()[40],
        workspace.Towers.ToH.Obby:GetChildren()[11],
        workspace.Towers.ToH.Obby:GetChildren()[18],
        workspace.Towers.ToH.Obby:GetChildren()[47],
        workspace.Towers.ToH.Obby:GetChildren()[15],
        workspace.Towers.ToH.Obby:GetChildren()[493],
        workspace.Towers.ToH.Obby:GetChildren()[10],
        workspace.Towers.ToH.Obby:GetChildren()[58],
        workspace.Towers.ToH.Obby:GetChildren()[26],
        workspace.ClientParts:GetChildren()[55].Platform,
        workspace.ClientParts:GetChildren()[52].Platform,
        workspace.ClientParts:GetChildren()[2].Platform,
        workspace.Towers.ToH.Obby:GetChildren()[659], --F7
        workspace.Towers.ToH.Obby:GetChildren()[640]
        
        
        
        
        
        
        

    }
end
